<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <RootNamespace>MatchMaking.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.13.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.13" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.13" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MatchMaking.Application\MatchMaking.Application.csproj" />
    <ProjectReference Include="..\MatchMaking.Contracts\MatchMaking.Contracts.csproj" />
    <ProjectReference Include="..\MatchMaking.Domain\MatchMaking.Domain.csproj" />
  </ItemGroup>

</Project>
